// Seed data for Prime Luxury Stays properties
// GPS coordinates are approximate based on the addresses provided

export const propertiesData = [
  {
    name: 'Vista Malgrat',
    slug: 'vista-malgrat',
    house_type: 'Villa',
    license_number: 'ETV/3730',
    registry_number: 'ESFCTU0000070210002684220000000000000000000ETV/37309',
    address: 'Calle Gaspar M. Jovellanos 42A, 07180 Santa Ponsa',
    city: 'Santa Ponsa',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.5089,
    longitude: 2.4789,
    bedrooms: 4,
    bathrooms: 4,
    max_guests: 8,
    description: 'Stunning villa in the prestigious area of Santa Ponsa with breathtaking views of the Malgrats Islands. This beautifully appointed property offers luxury living with modern amenities and traditional Mediterranean charm.',
    short_description: 'Luxury villa with stunning Malgrats Islands views in Santa Ponsa',
    featured_image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
    website_url: 'https://www.villa-vista-malgrat.com/',
    commission_percent: 22,
    has_pool: true,
    has_sea_view: true,
    has_ac: true,
    has_heating: true,
    is_active: true,
    is_featured: true,
    min_stay_nights: 7,
  },
  {
    name: 'Tres Reyes',
    slug: 'tres-reyes',
    house_type: 'Villa',
    license_number: 'ETV/6151',
    address: 'Calle Gaspar M Jovellanos 15A, 07180 Santa Ponsa',
    city: 'Santa Ponsa',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.5095,
    longitude: 2.4801,
    bedrooms: 4,
    bathrooms: 3,
    max_guests: 8,
    description: 'Beautiful family villa in the heart of Santa Ponsa. This exclusive property combines comfort with elegance, featuring spacious living areas and a private pool. Perfect for family getaways with July and August availability.',
    short_description: 'Elegant family villa in Santa Ponsa with private pool',
    featured_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    commission_percent: 22,
    has_pool: true,
    has_sea_view: false,
    has_ac: true,
    has_heating: true,
    is_active: true,
    is_featured: false,
    min_stay_nights: 7,
  },
  {
    name: 'Rosaclara',
    slug: 'rosaclara',
    house_type: 'Villa',
    license_number: 'ETV/6995',
    registry_number: 'ESFCTU000007032000041335000000000000000000008',
    address: 'Pol 7, Parcela 476 Carretera de Andratx a Capdella',
    city: 'Andratx',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.5756,
    longitude: 2.4189,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'Beautiful country house completely renovated in 2023. Set on a huge plot with its own forest, this stunning property features a gorgeous pool area surrounded by natural trees. Equipped with floor heating for winter and AC for summer comfort.',
    short_description: 'Newly renovated country house with private forest and pool',
    featured_image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    has_pool: true,
    has_sea_view: false,
    has_ac: true,
    has_heating: true,
    is_active: false, // Waiting for owner approval
    is_featured: false,
    min_stay_nights: 7,
  },
  {
    name: 'Sunset Dreams',
    slug: 'sunset-dreams',
    house_type: 'Villa',
    license_number: 'ETV/11530',
    registry_number: 'ESFCTU000007032000399900000000000000000000ETV/115302',
    address: 'Carrer Congre 62-64, 07157 Port d\'Andratx',
    city: 'Port d\'Andratx',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.5456,
    longitude: 2.3823,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'Exclusive villa in the prestigious Port d\'Andratx with spectacular sunset views over the Mediterranean. This luxury property offers the perfect blend of sophistication and comfort, ideal for those seeking the ultimate Mallorcan experience.',
    short_description: 'Prestigious Port d\'Andratx villa with Mediterranean sunset views',
    featured_image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
    commission_percent: 20,
    has_pool: true,
    has_sea_view: true,
    has_ac: true,
    has_heating: true,
    is_active: true,
    is_featured: true,
    min_stay_nights: 7,
  },
  {
    name: 'Sa Vinya',
    slug: 'sa-vinya',
    house_type: 'Finca',
    license_number: 'Pending',
    address: 'Near Cas Concos',
    city: 'Cas Concos',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.4312,
    longitude: 3.1456,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'First sea line house with breathtaking views and access to the sea. This modern, well-kept property features a live-in housekeeper and offers an unparalleled coastal living experience. Perfect for those seeking privacy and natural beauty.',
    short_description: 'First-line seafront finca with breathtaking coastal views',
    featured_image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&q=80',
    commission_percent: 20,
    has_pool: true,
    has_sea_view: true,
    has_ac: true,
    has_heating: true,
    is_beachfront: true,
    is_active: true,
    is_featured: true,
    min_stay_nights: 30, // Minimum 1 month as no license yet
  },
  {
    name: 'Eden Roc',
    slug: 'eden-roc',
    house_type: 'Villa',
    license_number: 'ETV/10399',
    address: 'Poligono 4, Parcela 75-7, 07640 Les Salines',
    city: 'Ses Salines',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.3423,
    longitude: 3.0567,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'Eden Roc is a fantastic property featuring a unique pool designed with a beach-style entry. Located in the sought-after Les Salines area, this villa offers a perfect retreat for those seeking luxury and tranquility.',
    short_description: 'Fantastic villa with beach-style pool in Les Salines',
    featured_image: 'https://images.unsplash.com/photo-1580541631950-7282082b53ce?w=1200&q=80',
    has_pool: true,
    has_sea_view: true,
    has_ac: true,
    has_heating: true,
    is_active: false, // Waiting for photos and pricelist
    is_featured: false,
    min_stay_nights: 7,
  },
  {
    name: 'Mariluz',
    slug: 'mariluz',
    house_type: 'Villa',
    license_number: 'ETV/12951',
    address: 'Calle Miro 65, Port d\'Andratx',
    city: 'Port d\'Andratx',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.5467,
    longitude: 2.3867,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'Stunning villa with panoramic sea views and harbour views of Port d\'Andratx. This exclusive property offers the perfect vantage point to enjoy the beauty of one of Mallorca\'s most prestigious ports.',
    short_description: 'Sea and harbour views in exclusive Port d\'Andratx',
    featured_image: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=1200&q=80',
    has_pool: true,
    has_sea_view: true,
    has_ac: true,
    has_heating: true,
    is_active: false, // Waiting for owner confirmation
    is_featured: false,
    min_stay_nights: 7,
  },
  {
    name: 'Puput Gran',
    slug: 'puput-gran',
    house_type: 'Finca',
    address: 'Canyamel',
    city: 'Canyamel',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.6534,
    longitude: 3.4312,
    bedrooms: 4,
    bathrooms: 8,
    max_guests: 8,
    description: 'Charming finca with pool and its own vineyard in the beautiful Canyamel area. This unique property combines traditional Mallorcan architecture with modern comforts, offering a truly authentic island experience.',
    short_description: 'Authentic finca with pool and private vineyard in Canyamel',
    featured_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    has_pool: true,
    has_sea_view: false,
    has_ac: true,
    has_heating: true,
    is_active: false, // Waiting for photographer
    is_featured: false,
    min_stay_nights: 7,
  },
  {
    name: '4 Elements',
    slug: '4-elements',
    house_type: 'Villa',
    license_number: 'ETV/10688',
    address: 'Bonaire, Alcudia',
    city: 'Alcudia',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.8312,
    longitude: 3.1234,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'Modern luxury villa in the exclusive Bonaire area of Alcudia. This stunning property represents the perfect harmony of design and nature, offering an exceptional retreat in northern Mallorca.',
    short_description: 'Modern luxury villa in exclusive Bonaire, Alcudia',
    featured_image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
    has_pool: true,
    has_sea_view: true,
    has_ac: true,
    has_heating: true,
    is_active: false, // Waiting for owner decision
    is_featured: false,
    min_stay_nights: 7,
  },
  {
    name: 'Bella Roca',
    slug: 'bella-roca',
    house_type: 'Villa',
    address: 'Capdella',
    city: 'Capdella',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.5234,
    longitude: 2.4567,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'Elegant villa nestled in the charming village of Capdella. Surrounded by the stunning Tramuntana mountain range, this property offers peace, privacy, and spectacular natural beauty.',
    short_description: 'Elegant villa surrounded by Tramuntana mountains',
    featured_image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
    has_pool: true,
    has_sea_view: false,
    has_ac: true,
    has_heating: true,
    is_active: false, // Waiting for photos
    is_featured: false,
    min_stay_nights: 7,
  },
  {
    name: 'Riviera',
    slug: 'riviera',
    house_type: 'Villa',
    address: 'Costa d\'en Blanes',
    city: 'Costa d\'en Blanes',
    region: 'Mallorca',
    country: 'Spain',
    latitude: 39.5389,
    longitude: 2.5678,
    bedrooms: 5,
    bathrooms: 5,
    max_guests: 10,
    description: 'Prestigious villa in Costa d\'en Blanes, one of Mallorca\'s most exclusive addresses. This sophisticated property offers luxury living with stunning sea views and proximity to Puerto Portals.',
    short_description: 'Prestigious villa in exclusive Costa d\'en Blanes',
    featured_image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    has_pool: true,
    has_sea_view: true,
    has_ac: true,
    has_heating: true,
    is_active: false, // Waiting for photos
    is_featured: false,
    min_stay_nights: 7,
  },
];

export const ownersData = [
  {
    property_slug: 'vista-malgrat',
    owner_name: 'Sabine and Andy Bohn',
    owner_phone: '+49 170 3406646',
    owner_email: 'sabinebohn@web.de',
    company_name: 'Bohn CB',
    is_agent: false,
  },
  {
    property_slug: 'tres-reyes',
    owner_name: 'Henry Werkmeister',
    owner_phone: '+49 173 2824781',
    owner_email: 'henry.werkmeister@moeller-ventures.de',
    is_agent: false,
  },
  {
    property_slug: 'rosaclara',
    owner_name: 'Villa Rosaclara S.L',
    is_agent: false,
    notes: 'Owner waiting for website to be ready before deciding on promotion',
  },
  {
    property_slug: 'sunset-dreams',
    owner_name: 'Dr Nikolaus Wacker',
    owner_phone: '+49 171 754 4532',
    owner_email: 'nikolaus@dr-wacker.com',
    is_agent: false,
  },
  {
    property_slug: 'sa-vinya',
    owner_name: 'Claudia Böttcher',
    owner_phone: '+34 634 321 672',
    owner_email: 'claudiaboettcher01@gmail.com',
    is_agent: false,
  },
  {
    property_slug: 'eden-roc',
    owner_name: 'Christine Schütz-Görnert',
    owner_phone: '+34 610 271 699',
    owner_email: 'cgcm.mallorca@gmail.com',
    is_agent: true,
  },
  {
    property_slug: 'mariluz',
    owner_name: 'Paul',
    owner_phone: '+34 610 093 949',
    is_agent: true,
  },
  {
    property_slug: 'puput-gran',
    owner_name: 'Bodo Dittmann',
    owner_phone: '+34 634 337 965',
    owner_email: 'bodo.dittmann@icloud.com',
    is_agent: false,
  },
];

